name: 🧪 Testing

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: install make
        run: choco install -y make
        if: runner.os == 'Windows'

      - name: make
        run: CC=gcc make

      - name: make check
        run: CC=gcc make check
