name: 🧪 Testing

on: push

env:
  CC: gcc
  # PREFIX: ${{ runner.temp }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, macos-13, macos-14, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: lista files 1
        run: ls C:\Program Files

      - name: lista files 2
        run: ls C:\Program Files\Common Files

      - name: install make
        run: choco install -y make
        if: runner.os == 'Windows'

      - name: make
        run: make

      - name: make check
        run: make check

      - name: make install
        run: make install
